### ISSUE TITLE
Blob error on file upload with multipart data

### ISSUE THREAD

**Issue by johanbook** [Kong/httpsnippet#160] opened 2020-03-26 09:08 UTC
I am trying to execute the following
```
  const snippet = new HTTPSnippet({
    method: "POST",
    url: "http://mockbin.com/har",
    headers: [
      {
        name: "content-type",
        value: "multipart/form-data"
      }
    ],
    postData: {
      mimeType: "multipart/form-data",
      params: [
        {
          name: "foo",
          fileName: "test/fixtures/files/hello.txt",
          contentType: "text/plain"
        }
      ]
    }
  });
```
but gets
```
TypeError: Failed to execute 'append' on 'FormData': parameter 2 is not of type 'Blob'.
```
in
```
  110 | request.postData.params.forEach(function (param) {
> 111 |   form.append(param.name, param.value || '', {
      | ^  112 |     filename: param.fileName || null,
  113 |     contentType: param.contentType || null
  114 |   })
```

Is there any error in my usage?

Can be related to #111

**Comment by darrenjennings** [comment] 2020-03-27 14:33
Duplicate of #111

**Closed as completed by darrenjennings** 2020-03-27 14:33 UTC

**Comment by SuhasParameshwara** [comment] 2022-12-26 14:24
I'm still facing this issue in 2.0.0. Any thoughts?
